version: '3'

services:
    client:
        container_name: tiktaktoe_client
        build: ./client
        volumes:
          - ./client:/var/www/client
        ports:
          - 3000:3000
        environment:
          - NODE_ENV=development
    